build: false
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"
    
    CONAN_UPLOAD: 1
    CONAN_REFERENCE: "libpng/1.6.21"
    CONAN_USERNAME: "lasote"
    CONAN_CHANNEL: "ci"
    CONAN_TOTAL_PAGES: 2
    
    matrix:
        - CONAN_CURRENT_PAGE: 1
        - CONAN_CURRENT_PAGE: 2  

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools # It install conan too
  - pip.exe install conan==0.0.1rc4
  - conan user # It creates the conan data directory

test_script:
  - python build.py
